from setuptools import setup, find_packages


setup(
    name='directory_components',
    version='39.1.4',
    url='https://github.com/uktrade/directory-components',
    license='MIT',
    author='Department for Business and Trade',
    description='Shared components library for Great services.',
    packages=find_packages(exclude=['tests.*', 'tests', 'scripts', 'demo.*', '*.css.map']),
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    include_package_data=True,
    install_requires=[
        'django>=1.11,<=4.2',
        'beautifulsoup4>=4.6.0,<5.0.0',
        'directory-constants>=23.1.0,<24.0.0',
        'jsonschema>=3.0.1,<4.0.0',
    ],
    extras_require={
        'test': [
            "lorem==0.1.1",
            "ansicolors==1.1.8",
            "gitdb==4.0.10",
            "gitpython==3.1.31",
            "GitPython",
            "flake8==3.7.8",
            "smmap==5.0.0",
            "toml==0.10.2",
            "requests-toolbelt==0.8.0",
            "twine>=1.11.0,<2.0.0",
            "wheel>=0.31.0,<1.0.0",
            "setuptools>=38.6.0,<39.0.0",
            "vulture>=1.0.0,<2.0.0",
            "hvac>=0.9.5,<1.0.0",
            "attrs==23.1.0",
            "certifi==2022.12.7",
            "charset-normalizer==3.1.0",
            "coverage[toml]==7.2.5",
            "execnet==1.9.0",
            "idna==3.4",
            "iniconfig==2.0.0",
            "packaging==23.1",
            "pluggy==0.13.1",
            "py==1.11.0",
            "pytest==6.2.1",
            "pytest-codecov==0.5.1",
            "pytest-cov==4.0.0",
            "pytest-django==3.10.0",
            "pytest-sugar==0.9.7",
            "pytest-xdist==3.2.1",
            "requests==2.30.0",
            "termcolor==2.3.0",
            "toml==0.10.2",
            "tomli==2.0.1",
            "urllib3==1.26.15",
            "codecov",   
        ],
        'demo': [
            'lorem==0.1.1',
            'django-environ==0.4.5',
            'gunicorn==19.5.0',
            'whitenoise==6.5.0',
            'django-pygments==0.5',
        ],
        'janitor': [
            'hvac>=0.9.5,<1.0.0',
            'vulture>=1.0.0,<2.0.0',
            'ansicolors>=1.1.8,<2.0.0',
        ]
    },
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Web Environment',
        'Framework :: Django',
        'Framework :: Django :: 1.11',
        'Framework :: Django :: 2.0',
        'Framework :: Django :: 2.1',
        'Framework :: Django :: 2.2',
        'Framework :: Django :: 3.1',
        'Framework :: Django :: 3.2',
        'Framework :: Django :: 4.1',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3.9',
        'Topic :: Software Development :: Libraries :: Python Modules',
    ]
)
